FROM gjchen/php7

RUN	apt-get update -y && apt-get dist-upgrade -y && \
	apt-get -y autoremove && apt-get -y autoclean && \
	rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* && \
	mkdir -p /app/public && mv /app/index.php /app/public

ENV	NGINX_SERVER_TPL="/etc/nginx/conf.d/laravel.template"

EXPOSE	80

