#!/bin/bash
[[ -f ./setup ]] && source ./setup
pushd /root > /dev/null
    PHP=$(/usr/sbin/phpquery -V)
    /usr/sbin/php-fpm${PHP} -p /etc/php/${PHP}/fpm -y /etc/php/${PHP}/fpm/php-fpm-www.conf -F
popd
